### ISSUE TITLE
Connection recovery does not work

### ISSUE THREAD

**Issue by ulfurinn** [koudelka/elixir-riemann#2]
This library and Honeydew don't seem to interact correctly.

If Riemann is down, `:gen_tcp.connect` can return, for example, `{:error, :econnrefused}`; this will cause a `MatchError` on `connection.ex:27` and crash the `Riemann.Connection` genserver. However, since it's spawned with `GenServer.start_link`, this will also crash the calling process, in this case a `Honeydew.Worker`, so the try/rescue block will not be able to intercept it, no delayed restart will happen, and standard OTP behaviours will kick in instead, resulting in the entire application crashing due to exceeded `max_restarts`.

This sort of use case is described here: http://inaka.net/blog/2012/11/29/every-day-erlang/

**Comment by koudelka** [comment]
Hey @ulfurinn, Is this something you've experienced in practice?

`Honeydew.Worker` is meant to crash in that case, and be restarted by its supervisor after a delay.

**Comment by ulfurinn** [comment]
Yes. The crash just propagates upwards.

**Comment by ulfurinn** [comment]
A simple workaround is:

``` elixir
defmodule Riemann.Worker do
  use Honeydew
  alias Riemann.Connection

  def init(args) do
    case Connection.start(args) do
      {:ok, pid} = ok ->
        Process.link(pid)
        ok
      x -> x
    end
  end
```

This allows the try/rescue block in `Honeydew.Worker` to engage as expected and try to restart with a delay.

I don't think this is a proper fix as there are probably crash scenarios it will not catch, but maybe it illustrates the issue a bit better.

**Comment by koudelka** [comment]
Sorry about that, I updated some behavior in Honeydew but didn't update riemann's dependency requirement to note that. Can you try what's on master?

**Comment by ulfurinn** [comment]
Seems to have done the trick.
